a=[]
f1=int(input("enter marks  :"))
a.append(f1)
f2=int(input("enter marks  :"))
a.append(f2)
f3=int(input("enter marks  :"))
a.append(f3)
f4=int(input("enter marks  :"))
a.append(f4)
f5=int(input("enter marks  :"))
a.append(f5)
f6=int(input("enter marks  :"))
a.append(f6)
a.sort()
print(a)