
s=set()
no=input("enter a number:")
s.add(int(no))
no=input("enter a number:")
s.add(int(no))
no=input("enter a number:")
s.add(int(no))
no=input("enter a number:")
s.add(int(no))
no=input("enter a number:")
s.add(int(no))
no=input("enter a number:")
s.add(int(no))
no=input("enter a number:")
s.add(int(no))

print(s)
